# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: st-lab4

on:
  push:
    branches: [ main ]
    tags:
      - '*'

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      
      - name: Grant permission for gradlew
        run: chmod +x gradlew

      - name: Build project
        run: gradle classes
        
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/build
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

  Test:
      needs: Build
      runs-on: ubuntu-latest
      
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-java@v1
          with:
            java-version: '11'
            
        - name: Cache
          uses: actions/cache@v2
          with:
            path: |
              ~/.gradle/caches
              ~/.gradle/wrapper
              ~/build
            key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
            restore-keys: |
              ${{ runner.os }}-gradle-
        
        - name: Grant permission for gradlew
          run: chmod +x gradlew
          
        - name: Run test
          run: gradle test --tests GameTest

        - uses: actions/upload-artifact@v2
          with:
              name: testReport
              path: build/reports

  Assemble:
      needs: Test
      runs-on: ubuntu-latest
      
      outputs:
        version: ${{ steps.getVersion.outputs.version }}

      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-java@v1
          with:
            java-version: '11'
        
        - name: Cache
          uses: actions/cache@v2
          with:
            path: |
              ~/.gradle/caches
              ~/.gradle/wrapper
              ~/build
            key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
            restore-keys: |
              ${{ runner.os }}-gradle-

        - name: Assemble
          run: gradle jar

        - id: getVersion
          run: echo "::set-output name=version::$(gradle printVersion)"
        
        - uses: actions/upload-artifact@v2
          with:
              name: buildJar
              path: build/libs/*.jar

  Release:
      if: startsWith(github.ref, 'refs/tags/')
      needs: Assemble
      runs-on: ubuntu-latest
      
      steps:
        - name: download artifact
          uses: actions/download-artifact@v2
        
        - uses: softprops/action-gh-release@v1
          with:
            files: |
              buildJar/st_nycu_lab4-${{ needs.Assemble.outputs.version }}.jar
          env: 
            GITHUB_TOKEN: ${{ secrets.LAB4_SECRET }}
