# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: st-lab4

on:
  push:
    branches: [ main ]
    tags:
      - '*'

  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build project
        run: gradle classes

  Test:
      runs-on: ubuntu-latest
      needs: Build
      steps:
        - uses: actions/checkout@v2
          
        - name: Run test
          run: gradle test --tests GameTest

        - uses: actions/upload-artifact@v2
          with:
              name: testReport
              path: build/reports

  Assemble:
      runs-on: ubuntu-latest
      needs: Test
      outputs:
        version: ${{ steps.getVersion.outputs.version }}

      steps:
        - uses: actions/checkout@v2

        - name: Assemble
          run: gradle jar

        - id: getVersion
          run: echo "::set-output name=version::$(gradle printVersion | head -n 3 | tail -n 1)"
        
        - uses: actions/upload-artifact@v2
          with:
              name: buildJar
              path: build/libs/*.jar

  Release:
      if: startsWith(github.ref, 'refs/tags/')
      runs-on: ubuntu-latest
      needs: Assemble
      steps:
        - uses: actions/download-artifact@v2
          name: buildJar
        
        - uses: softprops/action-gh-release@v1
          with:
            files: |
              buildJar/st_nycu_lab4-${{ needs.Assemble.outputs.version }}.jar
          env: 
            GITHUB_TOKEN: ${{ secrets.LAB4_SECRET }}
